# Tell Travis you want a Python environment to test in
sudo: false
language: python

# List the versions of Python you'd like to test against
python:
  - "3.5"
  - "3.6"

services:
  - rabbitmq
  - elasticsearch
  - postgresql

# List the versions of Django you'd like to test against
env:
  - DJANGO="Django>=1.10" TRAVIS="True"

addons:
  firefox: "47.0"

install:
   # install test requirements.
 - pip install -r tests/requirements.txt
   # Install the dependencies the app itself has
 - pip install git+https://github.com/aneumeier/feeds.git#latest
 - pip install coveralls
before_script:
  - psql -c 'create database myapp_test;' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# Tell Travis how to run the test script itself
script:
  - coverage run --source=feeds runtest.py -m py.test
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - http://angry-planet.com/webhook/travis
    on_success: always
    on_failure: never
